
// const ejecutar = () => {
//   return new Promise((resolve, reject) => {
//     resolve("Ã‰xito ðŸ˜º");
//   });
// };

// async function ejecutar (){
const ejecutar = async () => {
  return "Ã‰xito ðŸ˜º"; //resolve
  // throw "Algo fallÃ³! ðŸ˜·"; //reject

  //en algo como esto no se puede utilizar async por la sintaxis y el uso de la palabra reservada return
  // setTimeout(() => {
  //   return "Ã‰xito ðŸ˜º"; //resolve
  // }, 2000);
}
/*
ejecutar()
.then((resultado) => {
  console.log(resultado);
})
.catch((error) => {
  console.log(error)
})
*/
const comenzar = async () => {
  //trycatch me permite capturar errores, no solo de promesas
  try {
    //intenta esto
    const resultado = await ejecutar(); //then âŒ›
    console.log(resultado);
  } catch (error) { //catch
    console.log(error);
  }
}
comenzar();
