/*
const ejecutar = () => {
  return new Promise((resolve, reject) => {
    resolve("Ã‰xito ðŸ˜º");
  });
};
*/
// async function ejecutar (){
const ejecutar = async () => {
  // return "Ã‰xito ðŸ˜º"; //resolve
  throw "Algo fallÃ³! ðŸ˜·"; //reject
}
/*
ejecutar()
.then((resultado) => {
  console.log(resultado);
})
.catch((error) => {
  console.log(error)
})
*/
const comenzar = async () => {
  //trycatch me permite capturar errores, no solo de promesas
  try {
    //intenta esto
    const resultado = await ejecutar(); //then âŒ›
    console.log(resultado);
  } catch (error) { //catch
    console.log(error);
  }
}
comenzar();
